### ISSUE TITLE
Improper Service Configuration uuid.generator

### ISSUE THREAD

**Issue by bartundmett** [broadway/broadway-bundle#10]
When setting up the bundle i encountered a problem.

`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 6 passed to Broadway\EventStore\DBALEventStore::__cons
  truct() must be an instance of Broadway\UuidGenerator\Converter\BinaryUuidC
  onverterInterface`

The service "**broadway.uuid.generator**" is configured as "**Broadway\UuidGenerator\Rfc4122\Version4Generator.php**".

However when initializing the event store schema the DBALEventStore service (**broadway.event_store.dbal**) takes this service as sixt parameter. The constructor of that class expects  this to be "**BinaryUuidConverterInterface**" which it isn't.

**Comment by othillo** [comment]
fixed by https://github.com/broadway/broadway-bundle/pull/11

@5type The broadway/broadway-bundle project is still in development. You could use broadway/broadway 0.10.0 which has the current version of the bundle included.
