### ISSUE TITLE
Issue with matthiasnoback/symfony-service-definition-validator

### ISSUE THREAD

**Issue by mathewpeterson** [broadway/broadway-bundle#27]
This took a while for me to troubleshoot but I don't think you should use [`ValidateServiceDefinitionsPass`](https://github.com/broadway/broadway-bundle/blob/master/src/BroadwayBundle.php#L81).

The [`ValidateServiceDefinitionsPass`](https://github.com/matthiasnoback/symfony-service-definition-validator/blob/master/Compiler/ValidateServiceDefinitionsPass.php) runs validation for every service definition. In my case, using Symfony 3.2.4, there are 3 issues:
- sensio/framework-extra-bundle@3.0.22
  - [`Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener`](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/3.0/EventListener/SecurityListener.php#L39)
- symfony/monolog-bundle@3.0.3
  - [monolog.activation_strategy.not_found](https://github.com/symfony/monolog-bundle/blob/master/Resources/config/monolog.xml#L21)
  - [monolog.handler.fingers_crossed.error_level_activation_strategy](https://github.com/symfony/monolog-bundle/blob/master/Resources/config/monolog.xml#L22)

Per https://github.com/matthiasnoback/symfony-service-definition-validator#fixing-invalid-service-definitions-in-third-party-bundles, I created a new compiler pass to resolve these issues as well as disabling the `@security` annotation within sensio/framework-extra-bundle. I was able to load my app without errors.

Reading through the `matthiasnoback/symfony-service-definition-validator` documentation, it seems that you should be using [`Matthias\SymfonyServiceDefinitionValidator\ServiceDefinitionValidatorFactory`](https://github.com/matthiasnoback/symfony-service-definition-validator#service-validator-factory) instead. This could be done in a custom compile pass.

**Comment by othillo** [comment]
@mathewpeterson we reverted the commit that introduced this. 
It created more problems than it solved. 

Thanks for investigating. We can use this to properly test the service definition.
