### ISSUE TITLE
[RFC] decide on usage of doctrine-bundle by the commands

### ISSUE THREAD

**Issue by othillo** [broadway/broadway-bundle#29]
The broadway:event-store:schema commands require doctrine/doctrine-bundle.

Now that the DBAL event store is split from broadway/broadway and the opinionated DBAL implementation is (about to be) removed, it no longer makes sense to depend on the DoctrineBundle.

I suggest to remove the event store commands and describe how to create the events table in the README of the event-store-dbal project.

**Comment by haroldmodesto** [comment]
@othillo Where is the documentation mentioned above? I'm following the guide here https://github.com/broadway/event-store-dbal/pull/17. Is this the recommended way of creating the schema?
