### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by piotrkochan** [broadway/broadway-bundle#56]
Documentation is incomplete - https://broadway.github.io/broadway-bundle/

**Comment by sdecandelario** [comment]
Same here, the documentation is incomplete!

**Comment by piotrkochan** [comment]
Project looks abandoned

**Comment by AlessandroMinoccheri** [comment]
what is most needed at the moment in the documentation @piotrkochan ?
I could work on it, if it's possible.
