### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by ruudk** [broadway/broadway-bundle#6]
Would it be possible to tag a release and follow semver?

**Comment by wjzijderveld** [comment]
We already changed the branch-alias to 1.x in broadway, as we try to work towards a 1.0 release. Not sure when that will happen though 😄 

And as far as I know we have been following semver so far? 0.x releases are allowed to break BC... As long there is no 1.0 I suggest you lock it to a version

**Comment by maddy2101** [comment]
would still be nice to be able to require a tag. All I get until now is any *-dev versions, what messes with my other dependencies. Please, anything, whatever state, just tag it!

**Comment by othillo** [comment]
@ruudk, @maddy2101 I've tagged 0.1.0. Will follow semver for the planned BC breaks :sweat_smile:

**Comment by maddy2101** [comment]
\o/ thank you!
