### ISSUE TITLE
Symfony5 support

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [broadway/broadway-bundle#61]

**Comment by NikoGrano** [comment]
Bump

**Comment by NikoGrano** [comment]
Bump

**Comment by andyrooster** [comment]
I'd like to install this with Symfony 5. Would this just require an update to the dependancies config or is there breaking changes with Symfony 5?

Looks like some work has begun on this in master. Is there plans for a release?

**Comment by NikoGrano** [comment]
@andyrooster meanwhile if in hurry, feel free to use https://github.com/HouseHold/Broadway-bundle

Maintainers of this doesn't response these or PRs. Instead of that they install stale bot to close on going issues, which have went stale due lack of maintainers responsing

**Comment by andyrooster** [comment]
@othillo It looks like some (or maybe all) of the work is done on this in master. Is there plans for a new release any time soon?

**Comment by othillo** [comment]
Hey @andyrooster, I just tagged 0.5.0 with Symfony 5.0 support.

**Comment by andyrooster** [comment]
Hi @othillo thats great news, thanks very much, I really appreciate it 👍

**Comment by andyrooster** [comment]
@othillo I have installed this with Symfony 5 and it worked fine.

I did however run into a dependancy problem for broadway/event-store-dbal relying on broadway/uuid-generator ~0.4 which also seems to be resolved in that repo.

Will you be tagging event-store-dbal soon too?

**Comment by othillo** [comment]
@andyrooster I just tagged that [0.4.0](https://github.com/broadway/event-store-dbal/releases/tag/0.4.0).

**Comment by andyrooster** [comment]
Thank you
